---
- name: Link dotfiles
  hosts: localhost
  connection: local
  vars:
    - tmux_basepath: "{{ ansible_env.HOME }}"
    - tmux_links:
      - { src: "{{ playbook_dir }}/tmux/tmux",               dest: "{{ tmux_basepath }}/.tmux.conf" }
    - fish_basepath: "{{ ansible_env.HOME }}/.config/fish"
    - fish_links:
      - { src: "{{ playbook_dir }}/fish/config.fish",        dest: "{{ fish_basepath }}/config.fish" }
      - { src: "{{ playbook_dir }}/fish/functions",          dest: "{{ fish_basepath }}/functions" }
    - nvim_config_folder: "{{ ansible_env.HOME }}/.config/nvim"
    - git_basepath: "{{ ansible_env.HOME }}"
    - git_links:
      - { src: "{{ playbook_dir }}/git/gitconfig",           dest: "{{ git_basepath }}/.gitconfig" }
    - broot_basepath: "{{ ansible_env.HOME }}/.config/broot"
    - broot_links:
      - { src: "{{ playbook_dir }}/broot/conf.toml",         dest: "{{ broot_basepath }}/conf.toml" }
    #- vscode_basepath: "{{ ansible_env.HOME }}/.config/Code/User"
    - vscode_links:
      - { src: "{{ playbook_dir }}/vscode/settings.json",    dest: "{{ vscode_basepath }}/settings.json" }
      - { src: "{{ playbook_dir }}/vscode/keybindings.json", dest: "{{ vscode_basepath }}/keybindings.json" }
      - { src: "{{ playbook_dir }}/vscode/snippets",         dest: "{{ vscode_basepath }}/snippets" }
  tasks:
    - name: link tmux
      when: tmux_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ tmux_links }}"

    - name: create fish basepath
      when: fish_basepath is defined
      ansible.builtin.file:
        path: "{{ fish_basepath }}"
        state: directory
    - name: link fish
      when: fish_basepath is defined and fish_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ fish_links }}"

    - name: link nvim folder
      when: nvim_config_folder is defined
      ansible.builtin.file:
        src: "{{ playbook_dir }}/nvim"
        dest: "{{ nvim_config_folder }}"
        state: link

    - name: link git
      when: git_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ git_links }}"

    - name: create broot basepath
      when: broot_basepath is defined
      ansible.builtin.file:
        path: "{{ broot_basepath }}"
        state: directory
    - name: link broot
      when: broot_basepath is defined and broot_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ broot_links }}"

    - name: create vscode basepath
      when: vscode_basepath is defined
      ansible.builtin.file:
        path: "{{ vscode_basepath }}"
        state: directory
    - name: link vscode
      when: vscode_basepath is defined and vscode_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ vscode_links }}"

