---
- name: Link dotfiles
  hosts: localhost
  connection: local
  vars:
    - projects_dir: "{{ ansible_env.home }}/Projects"
    - tmux_basepath: "{{ ansible_env.home }}"
    - tmux_links:
        - {
            src: "{{ playbook_dir }}/tmux/tmux",
            dest: "{{ tmux_basepath }}/.tmux.conf",
          }
    - fish_basepath: "{{ ansible_env.home }}/.config/fish"
    - fish_links:
        - {
            src: "{{ playbook_dir }}/fish/config.fish",
            dest: "{{ fish_basepath }}/config.fish",
          }
        - {
            src: "{{ playbook_dir }}/fish/functions",
            dest: "{{ fish_basepath }}/functions",
          }
    - starship_basepath: "{{ ansible_env.home }}/.config"
    - starship_links:
        - {
            src: "{{ playbook_dir }}/starship/starship.toml",
            dest: "{{ starship_basepath }}/starship.toml",
          }
        - {
            src: "{{ playbook_dir }}/starship/starship-truncated.toml",
            dest: "{{ starship_basepath }}/starship-truncated.toml",
          }
    - git_basepath: "{{ ansible_env.home }}"
    - git_links:
        - {
            src: "{{ playbook_dir }}/git/gitconfig",
            dest: "{{ git_basepath }}/.gitconfig",
          }
    - zed_basepath: "{{ ansible_env.home }}/.config/zed"
    - zed_links:
        - {
            src: "{{ playbook_dir }}/zed/settings.json",
            dest: "{{ zed_basepath }}/settings.json",
          }
        - {
            src: "{{ playbook_dir }}/zed/keymap.json",
            dest: "{{ zed_basepath }}/keymap.json",
          }
    - vscode_basepath: "{{ ansible_env.home }}/.config/code/user"
    - vscode_links:
        - {
            src: "{{ playbook_dir }}/vscode/settings.json",
            dest: "{{ vscode_basepath }}/settings.json",
          }
        - {
            src: "{{ playbook_dir }}/vscode/keybindings.json",
            dest: "{{ vscode_basepath }}/keybindings.json",
          }
        - {
            src: "{{ playbook_dir }}/vscode/snippets",
            dest: "{{ vscode_basepath }}/snippets",
          }
    - git_repos:
        - {
            name: "mac_workstation",
            url: "https://github.com/lstwn/mac-workstation",
          }
        - { name: "dotfiles", url: "git@github.com:lstwn/dotfiles.git" }
        - { name: "blog", url: "git@github.com:lstwn/blog.git" }
        - { name: "masterthesis", url: "git@github.com:lstwn/masterthesis.git" }
        - {
            name: "undo_redo_replicated_registers",
            url: "git@github.com:lstwn/undo-redo-replicated-registers.git",
          }
        - { name: "lui", url: "ssh://git@git.lavego.de:7999/lui/lui.git" }
        - { name: "lusi", url: "ssh://git@git.lavego.de:7999/lui/lusi.git" }
        - { name: "levi", url: "ssh://git@git.lavego.de:7999/lui/levi.git" }
        - { name: "loak", url: "ssh://git@git.lavego.de:7999/lui/loak.git" }
        - {
            name: "luilibs",
            url: "ssh://git@git.lavego.de:7999/lui/luilibs.git",
          }
  tasks:
    - name: link tmux
      when: tmux_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ tmux_links }}"

    - name: create fish basepath
      when: fish_basepath is defined
      ansible.builtin.file:
        path: "{{ fish_basepath }}"
        state: directory
    - name: link fish
      when: fish_basepath is defined and fish_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ fish_links }}"

    - name: link starship
      when: starship_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ starship_links }}"

    - name: link git
      when: git_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ git_links }}"

    - name: create zed basepath
      when: zed_basepath is defined
      ansible.builtin.file:
        path: "{{ zed_basepath }}"
        state: directory
    - name: link zed
      when: zed_basepath is defined and zed_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ zed_links }}"

    - name: create vscode basepath
      when: vscode_basepath is defined
      ansible.builtin.file:
        path: "{{ vscode_basepath }}"
        state: directory
    - name: link vscode
      when: vscode_basepath is defined and vscode_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ vscode_links }}"

    - name: cloning git repos
      ansible.builtin.git:
        repo: "{{ item.url }}"
        dest: "{{ projects_dir }}/{{ item.name }}"
        update: no
      loop: "{{ git_repos }}"
