---
- name: Link dotfiles
  hosts: localhost
  connection: local
  vars:
    projects_dir: "{{ ansible_env.HOME }}/Projects"
    tmux_basepath: "{{ ansible_env.HOME }}"
    tmux_links:
      - {
          src: "{{ playbook_dir }}/tmux/tmux",
          dest: "{{ tmux_basepath }}/.tmux.conf",
        }
    fish_basepath: "{{ ansible_env.HOME }}/.config/fish"
    fish_links:
      - {
          src: "{{ playbook_dir }}/fish/config.fish",
          dest: "{{ fish_basepath }}/config.fish",
        }
      - {
          src: "{{ playbook_dir }}/fish/functions",
          dest: "{{ fish_basepath }}/functions",
        }
    ssh_basepath: "{{ ansible_env.HOME }}/.ssh"
    ssh_links:
      - {
          src: "{{ playbook_dir }}/ssh/config",
          dest: "{{ ssh_basepath }}/config",
        }
      - {
          src: "{{ playbook_dir }}/ssh/known_hosts",
          dest: "{{ ssh_basepath }}/known_hosts",
        }
    git_basepath: "{{ ansible_env.HOME }}"
    git_links:
      - {
          src: "{{ playbook_dir }}/git/gitconfig",
          dest: "{{ git_basepath }}/.gitconfig",
        }
    helix_basepath: "{{ ansible_env.HOME }}/.config/helix"
    helix_links:
      - {
          src: "{{ playbook_dir }}/helix/config.toml",
          dest: "{{ helix_basepath }}/config.toml",
        }
      - {
          src: "{{ playbook_dir }}/helix/languages.toml",
          dest: "{{ helix_basepath }}/languages.toml",
        }
    television_basepath: "{{ ansible_env.HOME }}/.config/television"
    television_links:
      - {
          src: "{{ playbook_dir }}/television/config.toml",
          dest: "{{ television_basepath }}/config.fish",
        }
      - {
          src: "{{ playbook_dir }}/television/cable",
          dest: "{{ television_basepath }}/cable",
        }
    efm_basepath: "{{ ansible_env.HOME }}/.config/efm-langserver"
    efm_links:
      - {
          src: "{{ playbook_dir }}/efm-langserver/config.yaml",
          dest: "{{ efm_basepath }}/config.yaml",
        }
    zed_basepath: "{{ ansible_env.HOME }}/.config/zed"
    zed_links:
      - {
          src: "{{ playbook_dir }}/zed/settings.json",
          dest: "{{ zed_basepath }}/settings.json",
        }
      - {
          src: "{{ playbook_dir }}/zed/keymap.json",
          dest: "{{ zed_basepath }}/keymap.json",
        }
    vscode_basepath: "{{ ansible_env.HOME }}/.config/code/user"
    vscode_links:
      - {
          src: "{{ playbook_dir }}/vscode/settings.json",
          dest: "{{ vscode_basepath }}/settings.json",
        }
      - {
          src: "{{ playbook_dir }}/vscode/keybindings.json",
          dest: "{{ vscode_basepath }}/keybindings.json",
        }
      - {
          src: "{{ playbook_dir }}/vscode/snippets",
          dest: "{{ vscode_basepath }}/snippets",
        }
    git_repos:
      - {
          name: "mac_workstation",
          url: "https://github.com/lstwn/mac-workstation",
        }
      - { name: "dotfiles", url: "git@github.com:lstwn/dotfiles.git" }
      - {
          name: "undo_redo_replicated_registers",
          url: "git@github.com:lstwn/undo-redo-replicated-registers.git",
        }
  tasks:
    - name: link tmux
      when: tmux_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ tmux_links }}"

    - name: create fish basepath
      when: fish_basepath is defined
      ansible.builtin.file:
        path: "{{ fish_basepath }}"
        state: directory
    - name: link fish
      when: fish_basepath is defined and fish_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      loop: "{{ fish_links }}"

    - name: create ssh basepath
      when: ssh_basepath is defined
      ansible.builtin.file:
        path: "{{ ssh_basepath }}"
        state: directory
    - name: link ssh
      when: ssh_basepath is defined and ssh_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      loop: "{{ ssh_links }}"

    - name: link git
      when: git_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ git_links }}"

    - name: create television basepath
      when: television_basepath is defined
      ansible.builtin.file:
        path: "{{ television_basepath }}"
        state: directory
    - name: link television
      when: television_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ television_links }}"

    - name: create helix basepath
      when: helix_basepath is defined
      ansible.builtin.file:
        path: "{{ helix_basepath }}"
        state: directory
    - name: link helix
      when: helix_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ helix_links }}"

    - name: create efm basepath
      when: efm_basepath is defined
      ansible.builtin.file:
        path: "{{ efm_basepath }}"
        state: directory
    - name: link efm
      when: efm_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ efm_links }}"

    - name: create zed basepath
      when: zed_basepath is defined
      ansible.builtin.file:
        path: "{{ zed_basepath }}"
        state: directory
    - name: link zed
      when: zed_basepath is defined and zed_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      loop: "{{ zed_links }}"

    - name: create vscode basepath
      when: vscode_basepath is defined
      ansible.builtin.file:
        path: "{{ vscode_basepath }}"
        state: directory
    - name: link vscode
      when: vscode_basepath is defined and vscode_links is defined
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ vscode_links }}"

    - name: cloning git repos
      ansible.builtin.git:
        repo: "{{ item.url }}"
        dest: "{{ projects_dir }}/{{ item.name }}"
        update: no
      loop: "{{ git_repos }}"
