blinking-cursor = false
performance = "High"
disable-unfocused-render = false
use-fork = false
line-height = 1.0
theme = "MacOS"
padding-x = 0.0
cursor = "▇"
env-vars = []
option-as-alt = "false"
ignore-selection-fg-color = false

[adaptive-theme]
light = "MacOS"
dark = "MacOS"

[navigation]
mode = "CollapsedTab"
use-current-path = false

[window]
width = 1600
height = 800
mode = "Windowed"

[background]

[shell]
program = ""
args = ["--login"]

[fonts]
size = 18.0
extras = []

[fonts.regular]
family = "JetBrains Mono"
weight = 600
style = "normal"

[fonts.bold]
family = "JetBrains Mono"
weight = 900
style = "normal"

[fonts.bold-italic]
family = "JetBrains Mono"
weight = 900
style = "italic"

[fonts.italic]
family = "JetBrains Mono"
weight = 600
style = "italic"

[developer]
enable-fps-counter = false
log-level = "OFF"

[bindings]
keys = []

